### ISSUE TITLE
I cannot set in .rr.yml Proto which includes other protos

### ISSUE THREAD

**Issue by oneslash** [spiral/php-grpc#15]
I cannot set in .rr.yml Proto which includes other protos.

It does not work for some reason

**Comment by wolfy-j** [comment]
Can you attach sample proto file and describe the issue in more details.

**Comment by oneslash** [comment]
**Category.proto**
```
syntax = "proto3";
package pim.v1;

message Category {
    uint32 id = 1;
    string name = 2;
}
```

**Product.proto**
```
syntax = "proto3";
package product;
import "v1/category.proto";

message Product {
    uint32 id = 1;
    string name = 2;
    Category primary_category = 3;
}
```

and my .rr.yml is
```

grpc:
  listen: "tcp://:9001"
  proto: "./vendor/yoni/pim-protobuf/v1/product.proto"
  workers:
    command: "php app.php"
    pool:
      numWorkers: 4
```
