### ISSUE TITLE
[RR2] Timeout error

### ISSUE THREAD

**Issue by hotrush** [spiral/php-grpc#59]
Our .rr.yaml contains:

```
limit:
  interval: 1
  services:
    grpc:
      maxMemory: 100
      TTL: 0
      idleTTL: 0
      execTTL: 3
```

When endpoint executes longer rr just kills the worker

```
ERRO[0006] 192.168.128.3:45344 Internal {3.104s} /Service/Endpoint worker error: EOF
ERRO[0006] worker.18 signal: killed
```

And client receives the next error message:

```
worker error: EOF
```

Is it possible to return more obvious error for cases like that?
